In [36]:
# 流程分析
# 1.获取数据
# 2.数据基本处理
# 2.1 数据量减小 对象.query("")
# 2.2 时间特征转换
#     pd.to_datetime(, unit="s")
#     pd.DatetimeIndex(time_value)
#     提取day,hour, weekday
# 2.3 去掉签到少的地点
#     acebook.groupby("place_id").count()
#     place_count[place_count["row_id"] > 3]
#     facebook[facebook["place_id"].isin(place_count.index)]
# 2.4 确定特征值,目标值
# 3.数据集划分
# 4.特征工程 -- 标准化
# 5.机器学习 -- knn
# 6.模型评估
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [3]:
# 1. 获取数据
data = pd.read_csv("./data/FBlocation/train.csv")

In [5]:
data.head()

   row_id       x       y  accuracy    time    place_id
0       0  0.7941  9.0809        54  470702  8523065625
1       1  5.9567  4.7968        13  186555  1757726713
2       2  8.3078  7.0407        74  322648  1137537235
3       3  7.3665  2.5165        65  704587  6567393236
4       4  4.0961  1.1307        31  472130  7440663949

In [26]:
# 2.数据基本处理
# 2.1 数据量减小 对象.query("")
facebook_data = data.query("x>2.0 & x<2.5 & y>4.0 & y<4.5")

In [27]:
facebook_data.head()

      row_id       x       y  accuracy    time    place_id
44        44  2.0768  4.4422        53  766037  1367769233
866      866  2.4639  4.0154       484  434568  5892845388
971      971  2.4423  4.2735        60  644739  3959611268
2236    2236  2.4842  4.1336         6  127826  9466102731
2811    2811  2.4197  4.3464         7   27104  9014138019

In [28]:
# 2.2 时间特征转换
#     pd.to_datetime(, unit="s")
#     pd.DatetimeIndex(time_value)
#     提取day,hour, weekday
time = pd.to_datetime(facebbok_data["time"], unit="s")
time = pd.DatetimeIndex(time)
facebook_data["hour"] = time.hour
facebook_data["day"] = time.day
facebook_data["weekday"] = time.weekday

/Users/sherwin/workspaces/ai/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/Users/sherwin/workspaces/ai/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/sherwin/workspaces/ai/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [29]:
facebook_data.head()

      row_id       x       y  accuracy    time    place_id  hour  day  weekday
44        44  2.0768  4.4422        53  766037  1367769233    20    9        4
866      866  2.4639  4.0154       484  434568  5892845388     0    6        1
971      971  2.4423  4.2735        60  644739  3959611268    11    8        3
2236    2236  2.4842  4.1336         6  127826  9466102731    11    2        4
2811    2811  2.4197  4.3464         7   27104  9014138019     7    1        3

In [31]:
# 2.3 去掉签到少的地点
#     acebook.groupby("place_id").count()
#     place_count[place_count["row_id"] > 3]
#     facebook[facebook["place_id"].isin(place_count.index)]
place_count = facebook_data.groupby("place_id").count()
place_count = place_count[place_count["row_id"]>3]
facebook_data = facebook_data[facebook_data["place_id"].isin(place_count.index)]

In [32]:
# 2.4 确定特征值,目标值
x = facebook_data[["x", "y", "accuracy", "hour", "day", "weekday"]]
y = facebook_data["place_id"]

In [34]:
x.head()

           x       y  accuracy  hour  day  weekday
44    2.0768  4.4422        53    20    9        4
866   2.4639  4.0154       484     0    6        1
971   2.4423  4.2735        60    11    8        3
2236  2.4842  4.1336         6    11    2        4
2811  2.4197  4.3464         7     7    1        3

In [37]:
# 3.数据集划分
# 4.特征工程 -- 标准化
# 5.机器学习 -- knn
# 6.模型评估


# 2.数据集分割
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=22)

# 3.特征工程 -- 标准化
# 3.1 实例化一个转换器
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

# 4.机器学习 -- knn + 交叉验证,网格搜索
# 4.1 实例化一个knn估计器
estimator = KNeighborsClassifier()
# 4.2 调用交叉验证,网格搜索api
param_grid = {"n_neighbors": [1, 3, 5, 7]}
estimator = GridSearchCV(estimator, param_grid=param_grid, cv=5)
# 4.3 通过grid_cv模型训练
estimator.fit(x_train, y_train)

# 5.模型评估
score = estimator.score(x_test, y_test)
print("模型 的准确率为:\n", score)
y_predict = estimator.predict(x_test)
print("最后的预测结果:\n", y_predict == y_test)

# 5.1 其他评估方式
print("在交叉验证中验证的最好结果:\n",estimator.best_score_)
print("最好的参数模型:\n", estimator.best_estimator_)
print("每次交叉验证后的验证集准确率结果和训练集准确率结果:\n", estimator.cv_results_)

/Users/sherwin/workspaces/ai/lib/python3.6/site-packages/sklearn/model_selection/_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)

模型 的准确率为:
 0.38730055001906005
最后的预测结果:
 18076813     True
25101338    False
15636175     True
25876091    False
6879         True
16717806     True
20987494    False
10456538    False
603533       True
17892607     True
23462680    False
24473252     True
17015629     True
27866390     True
24431560     True
27560776    False
28318322    False
26987220    False
25524103     True
10980380    False
26117380     True
25328488     True
12078667    False
22831800     True
8119342     False
10152908     True
23846708    False
12380648     True
2512531     False
5911213     False
            ...
24020532     True
24875289    False
23468875    False
20604187    False
8881738      True
23618433    False
12014636     True
3781991     False
8203422     False
19038356    False
1046876      True
14930027     True
7623074      True
23067599     True
24568518    False
24969895    False
17219620    False
22812053     True
11762820     True
11872975     True
7408610      True
8638080      True
24851974     True
6756044     False
28647560    False
6065983      True
19749621     True
26108942    False
10516343     True
17822724    False
Name: place_id, Length: 18363, dtype: bool
在交叉验证中验证的最好结果:
 0.36991050844996276
最好的参数模型:
 KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')
每次交叉验证后的验证集准确率结果和训练集准确率结果:
 {'mean_fit_time': array([0.05706382, 0.05687504, 0.06054106, 0.0533927 ]), 'std_fit_time': array([0.00641   , 0.0042622 , 0.01052214, 0.00222326]), 'mean_score_time': array([0.16526599, 0.35475278, 0.43048902, 0.46726022]), 'std_score_time': array([0.0071173 , 0.00910138, 0.01417315, 0.00904941]), 'param_n_neighbors': masked_array(data=[1, 3, 5, 7],
             mask=[False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'n_neighbors': 1}, {'n_neighbors': 3}, {'n_neighbors': 5}, {'n_neighbors': 7}], 'split0_test_score': array([0.352     , 0.35147253, 0.36087912, 0.35894505]), 'split1_test_score': array([0.35869759, 0.35477252, 0.36663693, 0.3618198 ]), 'split2_test_score': array([0.36689018, 0.36090975, 0.36797753, 0.36824937]), 'split3_test_score': array([0.36830934, 0.36000369, 0.37338501, 0.37356958]), 'split4_test_score': array([0.37725734, 0.36484199, 0.38148984, 0.38101956]), 'mean_test_score': array([0.36442847, 0.35829294, 0.36991051, 0.36853092]), 'std_test_score': array([0.00863238, 0.00472782, 0.00692987, 0.00795294]), 'rank_test_score': array([3, 4, 1, 2], dtype=int32), 'split0_train_score': array([1.        , 0.61190923, 0.55103628, 0.51258178]), 'split1_train_score': array([1.        , 0.6117505 , 0.54948837, 0.51126963]), 'split2_train_score': array([1.        , 0.61006061, 0.54561551, 0.50906862]), 'split3_train_score': array([1.        , 0.6103767 , 0.54681039, 0.50855309]), 'split4_train_score': array([1.        , 0.60804823, 0.54452617, 0.50612952]), 'mean_train_score': array([1.        , 0.61042905, 0.54749534, 0.50952053]), 'std_train_score': array([0.        , 0.00139599, 0.00242195, 0.00223918])}